apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sb3d0190c-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sb3d0190c-java-quarkus-gitops